import { readdirSync, existsSync, copyFileSync } from 'fs'
import { join, extname, basename, dirname } from 'path'
import { writeJson } from '../core/jsonIO'
import { readEnUsFromJar, choosePrimaryModId } from '../core/jarReader'

export interface JarEntry {
  jarPath: string
  modId: string
  enUsEntries: Record<string, string>
}

export function scanModsDir(modsDir: string): JarEntry[] {
  if (!existsSync(modsDir)) return []

  const results: JarEntry[] = []
  let files: string[]
  try {
    files = readdirSync(modsDir)
  } catch {
    return []
  }

  for (const file of files) {
    if (extname(file).toLowerCase() !== '.jar') continue
    const jarPath = join(modsDir, file)
    const modMaps = readEnUsFromJar(jarPath)
    const primary = choosePrimaryModId(modMaps)
    if (!primary) continue
    results.push({ jarPath, modId: primary.modId, enUsEntries: primary.entries })
  }

  return results
}

export function inferOutDir(modsDir: string): string {
  const parent = dirname(modsDir)
  const grandparent = dirname(parent)
  const packName = basename(grandparent) || basename(parent)
  return join(parent, 'resourcepacks', `${packName}_localize`)
}

const PACK_MCMETA = JSON.stringify(
  { pack: { pack_format: 34, description: 'Generated by MCModLocalizer' } },
  null,
  2,
)

export function buildResourcePackMeta(outDir: string, appIconPath: string | null): void {
  writeJson(join(outDir, 'pack.mcmeta'), JSON.parse(PACK_MCMETA))
  const packPng = join(outDir, 'pack.png')
  if (!existsSync(packPng) && appIconPath && existsSync(appIconPath)) {
    copyFileSync(appIconPath, packPng)
  }
}
